<a href="https://colab.research.google.com/github/JasmineLee7/movie-rec/blob/main/notebooks/01_ratings_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
print("hello")

hello

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Part A: A Small Ratings Matrix

Rows represent users, and columns represent movies.
Ratings range from 1 to 5 stars. NaN represents a missing rating.

In [7]:
movies = ["Action 1", "Action 2", "Action 3",
          "Romance 1", "Romance 2", "Romance 3"]

users = ["Ana", "Ben", "Cal", "Dee", "Eve", "Fay"]

In [8]:
toy = np.array([
    [5, 4, 5, 1, np.nan, 2],       # Ana
    [4, np.nan, 5, 2, 1, 1],       # Ben
    [5, 5, np.nan, 1, 2, np.nan],  # Cal
    [1, 2, 1, 5, 4, np.nan],       # Dee
    [np.nan, 1, 2, 4, 5, 5],       # Eve
    [2, 1, np.nan, 5, np.nan, 4],  # Fay
])

toy_table = pd.DataFrame(toy, index=users, columns=movies)
toy_table

     Action 1  Action 2  Action 3  Romance 1  Romance 2  Romance 3
Ana       5.0       4.0       5.0        1.0        NaN        2.0
Ben       4.0       NaN       5.0        2.0        1.0        1.0
Cal       5.0       5.0       NaN        1.0        2.0        NaN
Dee       1.0       2.0       1.0        5.0        4.0        NaN
Eve       NaN       1.0       2.0        4.0        5.0        5.0
Fay       2.0       1.0       NaN        5.0        NaN        4.0

In [9]:
missing = np.isnan(toy).sum()
print("Missing entries:", missing, "out of", toy.size)

Missing entries: 8 out of 36

## Exercise 1: Predicting Missing Ratings

| User | Movie | Predicted rating |
|---|---|---|
| Ana | Romance 2 | 1 |
| Ben | Action 2 | 4 |
| Cal | Action 3 | 5 |
| Cal | Romance 3 | 1 |
| Dee | Romance 3 | 5 |
| Eve | Action 1 | 1 |
| Fay | Action 3 | 2 |
| Fay | Romance 2 | 5 |

Ana — Romance 2: I predicted 1 star because Ana gave Romance 1 a 1 and Romance 3 a 2, suggesting she dislikes romance movies. Ben has similar preferences: both rate action movies highly and romance movies poorly. Ben gave Romance 2 a 1, which supports my prediction.

Cal — Action 3: I predicted 5 stars because Cal gave both Action 1 and Action 2 a 5. Ana and Ben also enjoy action movies, and both gave Action 3 a 5. Their ratings support predicting that Cal would give it 5 stars too.

## Exercise 2: Adding a seventh user

Gus likes action movies and dislikes romance movies, like Ana, Ben, and Cal.
He rated four movies and has not rated Action 3 or Romance 3.

In [10]:
gus = np.array([5, 4, np.nan, 1, 2, np.nan])
toy7 = np.vstack([toy, gus])
users7 = users + ["Gus"]

toy7_table = pd.DataFrame(toy7, index=users7, columns=movies)
toy7_table

     Action 1  Action 2  Action 3  Romance 1  Romance 2  Romance 3
Ana       5.0       4.0       5.0        1.0        NaN        2.0
Ben       4.0       NaN       5.0        2.0        1.0        1.0
Cal       5.0       5.0       NaN        1.0        2.0        NaN
Dee       1.0       2.0       1.0        5.0        4.0        NaN
Eve       NaN       1.0       2.0        4.0        5.0        5.0
Fay       2.0       1.0       NaN        5.0        NaN        4.0
Gus       5.0       4.0       NaN        1.0        2.0        NaN

Gus gave Action 1 a 5, Action 2 a 4, Romance 1 a 1, and Romance 2 a 2.
His two missing ratings are Action 3 and Romance 3.

| User | Movie | Predicted rating |
|---|---|---|
| Gus | Action 3 | 5 |
| Gus | Romance 3 | 1 |

**Gus: Action 3: predicted 5.** Gus's observed ratings closely match Ana's
(5, 4, ..., 1) and Ben's (4, ..., 2, 1), who both like action and dislike
romance. Ana and Ben each gave Action 3 a 5. Dee and Eve, who have the opposite
taste, rated Action 3 only a 1 and a 2, which is consistent with Gus
being on the other side of that split.

**Gus: Romance 3: predicted 1.** Gus gave low ratings to Romance 1 and
Romance 2, so he seems to dislike the romance group. Ana (2) and Ben (1) also
rated Romance 3 low. Because Gus is slightly harsher on romance than Ana,
I predict 1 rather than 2.